[package]
name = "oscar-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "oscar"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.7" }
indicatif = { version = "0.18.6", default-features = false, features = ["unicode-width"] }
oscar-core = { path = "../oscar-core" }
serde_json = "1.0"
tokio = { version = "1", features = ["rt-multi-thread", "signal", "macros", "time"] }

[dev-dependencies]
indicatif = { version = "0.18.6", default-features = false, features = ["in_memory"] }

[features]
default = []
http = ["oscar-core/http"]
